import type { Metadata } from "next";
import { Geist, Geist_Mono, Quicksand } from "next/font/google";
import Providers from "@/providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quickSand = Quicksand({
  variable: "--font-quick-sand",
  subsets: ["latin", "latin", "vietnamese"],
});

export const metadata: Metadata = {
  title: "Notewords",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${quickSand.className} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
